// <auto-generated />
using System;
using Ireckonu.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ireckonu.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190818211214_initial_create")]
    partial class initial_create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ireckonu.DomainModel.IruData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArticleCode");

                    b.Property<string>("Color");

                    b.Property<string>("ColorCode");

                    b.Property<string>("DeliveredIn");

                    b.Property<string>("Description");

                    b.Property<double>("DiscountPrice");

                    b.Property<string>("Key");

                    b.Property<double>("Price");

                    b.Property<string>("Q1");

                    b.Property<int>("Size");

                    b.HasKey("Id");

                    b.ToTable("IruData");
                });
#pragma warning restore 612, 618
        }
    }
}
